### ISSUE TITLE
[QUESTION] Conan C++ support

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasmtime-cpp#1]
Do you consider supporting Conan C++ as package manager for this wrapper ?

**Comment by alexcrichton** [comment]
I think that'd be fine to add! For me at least this is the first piece of C++ I've ever published as a library, so I'm pretty new to this. I've never worked with Conan myself, but would you be up for sending a PR? Ideally it'd include CI to test the build configuration too

**Comment by redradist** [comment]
It would require to write pr into [conan-center-index](https://github.com/conan-io/conan-center-index)

**Comment by alexcrichton** [comment]
Ah ok, well if I can help out with that let me know! I unfortunately don't know enough about Conan to make a PR myself though.

**Comment by redradist** [comment]
I know how to do it ...

Do you need a help with this wrapper ?
If I would have some time I can help with it I know C++ and Rust, but unfortunately I do not understand current status of this wrapper ... I mean how much is finished and so on

**Comment by redradist** [comment]
Also seems like conan is not needed for current implementation because all wrapper functionallity is header only ...
Do you plan to make separate cpp file for better maintainability ?

**Comment by alexcrichton** [comment]
Oh no the wrapper is ready to go and can be used whenever. It's header-only because the actual implementation comes from `libwasmtime.so` which is the C API of wasmtime. The C++ is currently built on the C API and doesn't need any extra accompanying `*.cpp` files.

**Comment by alexcrichton** [comment]
er sorry didn't mean to close..

I meant to say though that I don't know if Conan supports header-only libraries? Or if it supports a header-only library with a Rust C API as a backend?

**Comment by redradist** [comment]
> 
> 
> er sorry didn't mean to close..
> 
> I meant to say though that I don't know if Conan supports header-only libraries? Or if it supports a header-only library with a Rust C API as a backend?

@alexcrichton Yes, conan supports header only library, but during installation it also verify system dependencies, compiler versions and so on

Actually, conan for C++ (with conanfile.txt) is like cargo for Rust (with Cargo.toml)

**Comment by redradist** [comment]
@alexcrichton 
> 
> 
> Oh no the wrapper is ready to go and can be used whenever. It's header-only because the actual implementation comes from `libwasmtime.so` which is the C API of wasmtime. The C++ is currently built on the C API and doesn't need any extra accompanying `*.cpp` files.

Does it mean that `wasmtime.hh` was just generated for wasmtime-cpp ?

**Comment by alexcrichton** [comment]
The `wasmtime.hh` header was hand-written and isn't generated (intentionally). It depends on `libwasmtime.so`, the Rust-based C API of Wasmtime, but otherwise this repository houses the `wasmtime.hh` to be separately tested from the main `wasmtime` repo itself.

**Comment by redradist** [comment]
It think I would have some time on the week to create receipt for wasmtime-cpp, but it could require small changes in CMakeLists.txt

**Comment by alexcrichton** [comment]
Oh that's fine! This was the first time I've ever written a `CMakeLists.txt` so changes are more than welcome

**Comment by redradist** [comment]
@alexcrichton What kind of features from C++20 do you use ?
Currently no major compiler supports C++20 completely ...

**Comment by alexcrichton** [comment]
I believe it's only the `std::span` type, which at least is supported by the compilers tested on CI here

**Comment by redradist** [comment]
@alexcrichton Here is initial receipt for `wasmtime` in conan-center
Then I will added separate package `wasmtime-cpp` that will have dependency on `wasmtime`

**Comment by redradist** [comment]
@alexcrichton 
I expect that soon conan package for wasmtime will be merged ...
For working on wasmtime-cpp package we need to have tags for releases

Do you consider adding tags for versions ?

**Comment by alexcrichton** [comment]
Sure! I just pushed up a v0.28.0 tag

**Comment by redradist** [comment]
@alexcrichton The basic wasmtime package almost merged ...
Do you plan have in sync versions of wasmtime-cpp and wasmtime ?

I need it to know for making next package for wasmtime-cpp ...
If yes, then we need extra tag for release 0.29 ?

**Comment by redradist** [comment]
@alexcrichton I have create PR in wasmtime for C Conan package https://github.com/bytecodealliance/wasmtime/pull/3307
Soon I will create CPP Conan package ...

**Comment by redradist** [comment]
@alexcrichton I've started working on wasmtime-cpp packaging https://github.com/conan-io/conan-center-index/pull/7188

**Comment by alexcrichton** [comment]
Awesome, thanks! Let me know if you need anything from my end.

The plan is indeed to have the wasmtime-cpp and wasmtime versions sync'd. I don't know really where to specify a version in this repository beyond tags, but I can create a 0.29 tag if so necessary.

**Comment by redradist** [comment]
@alexcrichton Seems like you added `wasmtime_memorytype_minimum` function is missed in release of `wasmtime` https://github.com/bytecodealliance/wasmtime/releases/tag/v0.29.0

It means you need to change commit for tag v0.29.0 otherwise dependencies do not works

**Comment by alexcrichton** [comment]
Oops sorry yeah I'll try to find a better 0.29.0 tag later this week.

**Comment by redradist** [comment]
@alexcrichton There are only two possible commits _**Fix including wasmtime.hh in multiple CGUs (#9)**_ 3ee46ce698c909f18e4fc9c29249002e03fe4510 and **_Instead of converting wasmtime::Span added ifdef with type alias for …_** 69829db5fbd8eff647ebf1b03a9b4efaa0149c90

**Comment by alexcrichton** [comment]
Ok I've updated the v0.29.0 tag to be the same as the v0.28.0 tag since that's the latest commit that works.

**Comment by redradist** [comment]
@alexcrichton Thanks a lot !!
Receipt was updated, I expect it soon to be merged

**Comment by redradist** [comment]
@alexcrichton PR merged !!
https://github.com/conan-io/conan-center-index/pull/7188

**Comment by redradist** [comment]
@alexcrichton Now when you will have new release for wasmtime just create PR to https://github.com/conan-io/conan-center-index and add new version to receipt https://github.com/conan-io/conan-center-index/tree/master/recipes/wasmtime in `config.yml` and `conandata.yml`

The same for wasmtime-cpp https://github.com/conan-io/conan-center-index/tree/master/recipes/wasmtime-cpp

**Comment by alexcrichton** [comment]
Ok great! I'll probably lean on you to update the conan packages, but would you like me to notify you on releases/tags?

**Comment by redradist** [comment]
> 
> 
> Ok great! I'll probably lean on you to update the conan packages, but would you like me to notify you on releases/tags?

Yeah, would be nice ... I will provide PR and you will learn how to update package version by yourself

**Comment by alexcrichton** [comment]
Ok, I'm going to close this because I think this is done now.
