### ISSUE TITLE
do not include iostream in the public header

### ISSUE THREAD

**Issue by swang206** [bytecodealliance/wasmtime-cpp#18]
The problem is that iostream will inject static variable for each translation unit, that bloats binary size.
Use iosfwd instead.

**Comment by alexcrichton** [comment]
Oh I was unaware of this, thanks for the suggestion!

**Comment by dshiell15** [comment]
I notice that after this change I see compilation errors complaining about cerr not existing in std. This is on Ubuntu 18.04.

```.../wasmtime.hh:185:10: error: ‘cerr’ is not a member of ‘std’```

**Comment by swang206** [comment]
> I notice that after this change I see compilation errors complaining about cerr not existing in std. This is on Ubuntu 18.04.
> 
> `.../wasmtime.hh:185:10: error: ‘cerr’ is not a member of ‘std’`
> 
> Also stream operator<< errors like:
> 
> ```
> wasmtime.hh:489:8: error: no match for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ a
> nd ‘const char [5]’)                                                                
>      os << "v128";                                                              
>      ~~~^~~~~~~~~
> ```

then #include<ostream>, not <iostream>

**Comment by dshiell15** [comment]
Thanks! Yes, sorry I meant to follow up my comment with your suggestion. I made this change and it works fine - though I found I still need to use iostream since cerr is defined in iostream and is used in wasmtime::Result::abort() which is giving me these issues.

Does it mean though that everywhere wasmtime is included one would end up being required to include <iostream> anyway? Maybe I missing something?

**Comment by swang206** [comment]
> Thanks! Yes, sorry I meant to follow up my comment with your suggestion. I made this change and it works fine - though I found I still need to use iostream since cerr is instantiated in iostream and is used in wasmtime::Result::abort() which is giving me these issues.
> 
> Does it mean though that everywhere wasmtime is included one would end up being required to include ostream anyway? Maybe I missing something?

then use stdio.h

**Comment by tearosccebe** [comment]
> Thanks! Yes, sorry I meant to follow up my comment with your suggestion. I made this change and it works fine - though I found I still need to use iostream since cerr is instantiated in iostream and is used in wasmtime::Result::abort() which is giving me these issues.
> 
> Does it mean though that everywhere wasmtime is included one would end up being required to include ostream anyway? Maybe I missing something?

first. do not use abort() as name since some libcs might define it as macros.


then you
```cpp
#include<cstdio>

fprintf(stderr,"error: %s\n",this->err().message());

std::terminate() or std::abort() or __builtin_trap();
```

BTW, i do not think unwrap() is a good design tbh.

**Comment by alexcrichton** [comment]
Does https://github.com/bytecodealliance/wasmtime-cpp/pull/21 solve the issues recently described here?

**Comment by dshiell15** [comment]
Yes, #21 is a definite improvement! I now can include <ostream> instead of <iostream>. It looks like ostream is still required by ValKind for example: https://github.com/bytecodealliance/wasmtime-cpp/blob/main/include/wasmtime.hh#L468

Would it makes sense to include <ostream> in the wasmtime.hh? I'm not sure what the standard practices are for public headers like this?

**Comment by alexcrichton** [comment]
Ah yeah sorry I'm not super experienced in writing C++ libraries so I also don't know what to do here in that regard. I'm also surprised I haven't seen any of this in testing. Do you know how I would be able to reproduce these errors myself?

**Comment by tearosccebe** [comment]
> Ah yeah sorry I'm not super experienced in writing C++ libraries so I also don't know what to do here in that regard. I'm also surprised I haven't seen any of this in testing. Do you know how I would be able to reproduce these errors myself?

Actually not including iostream is extremely important in wasm since just include iostream bloats 1MB of binary size (if you are using libstdc++) or 400 kb for libc++. Which is extremely large.
WASM is designed for small binary size, iostream is something you should never ever use tbh.

**Comment by dshiell15** [comment]
Yeah, @alexcrichton - I had the same thought. I think maybe the gtest.h header is including ostream which is why it doesn't show in the testsuite?
