### ISSUE TITLE
wasmtime_store_limiter not wrapped

### ISSUE THREAD

**Issue by agutekanst-llnw** [bytecodealliance/wasmtime-cpp#36]
Hello 👋 

I've recently had a need to use the [store limiter that is provided in wasmtime (`wasmtime_store_limiter`)](https://github.com/bytecodealliance/wasmtime/blob/6554077aca3575500e2fba0ebcbea1f8ac18bdea/crates/c-api/include/wasmtime/store.h#L82-L118), but it only seems to be exposed in the C API currently.

Is this intentional, or should I wrap the function and send a PR?

Thanks

**Comment by alexcrichton** [comment]
Nah not intentionally omitted, just wasn't there when the bindings were written. A PR to add this would be much appreciated!
