### ISSUE TITLE
Any liat of Supported datatypes

### ISSUE THREAD

**Issue by am2222** [bytecodealliance/wasmtime-cpp#49]
Hi,
I am planning to use wasmtime to compile a cpp library to webassembely. The library I am using utilities the following datatypes
`Long long`
`Uint_64`

Most of the functions I am porting get one or two vector of these types and return another vector. I checked the examples page and noticed wasmtime supports some of these types like uint_64 but was wondering if  vector function arguments and outputs are supported or not?

I noticed like in case of emscripten they have their own wrapper data type to support vector to js array!

Thanks!

**Comment by alexcrichton** [comment]
I'll note that wasmtime-cpp is for running WebAssembly binaries in C++, not for compiling WebAssembly binaries to C++. If your WebAssembly guest is using vectors then the representation of how the host works with that depends on the toolchain, language, and types that you're using. 

The `wasmtime-cpp` bindings, however, have no specialized handling of types like vectors or strings, it's up to embedders to handle all that.

**Comment by am2222** [comment]
Thanks @alexcrichton 
May I ask what cpp toolchain is more compatible with wasmtime? 

Thanks!

**Comment by alexcrichton** [comment]
I am personally familiar with [wasi-sdk](https://github.com/bytecodealliance/wasi-sdk) but the Emscripten toolchain may work too. I'm not sure myself though about Emscripten/WASI. The binaries produced by wasi-sdk rely on WASI imports which Wasmtime has knobs to enable pretty easily

**Comment by am2222** [comment]
Thanks @alexcrichton 
I am already working with Emscripten but their toolchian does not make a fully wasi compatible files and I have to change to something more compatible!
