### ISSUE TITLE
[Bug] Impossible to include "wasmtime.hh" multiple times (multiple definition errors at linking)?

### ISSUE THREAD

**Issue by sschnug** [bytecodealliance/wasmtime-cpp#8]
Hello,

being new to WebAssembly, i tried to implement a WASM-based plugin-concept. The wasmtime project looks awesome and a first hello-world like example (with some additions like using a flatbuffers-based plugin-api to ease non-fundamental data-type passing) worked great.

Then i tried to flesh out the example to something bigger.
**In it's essence, we are just talking about increasing the cardinality of compilation-units here**.

Without being an expert C++ developer, **i carefully ask if it's possible, that the current implementation is broken in some sense as we cannot include "wasmtime.hh" multiple times without violating the one-definition rule?** 

My problem exactly looks like [this StackOverflow question](https://stackoverflow.com/a/29196891/2320035) (please don't be offended by the negative tone there).

Here is a minimal example (which does not make sense in this state) which should fail for you too (i guess):

# Problem Demo

### `run.cc`

    #include <iostream>
    
    #include "wasm_backend.hh"
    
    int main() {
      std::cout << "hello" << std::endl; 
      return 0;
    }

### `wasm_backend.hh`

    #pragma once // same with "classic" include-guards
   
    // This include leads to linking-errors 
    #include <wasmtime.hh>
  
    class WasmBackend {};

### `wasm_backend.cc`

    #include "wasm_backend.hh"

    // no other code here

# Compilation

    clang++ run.cc wasm_backend.cc -std=c++20 -I third_party/wasmtime-v0.28.0-x86_64-linux-c-api/include third_party/wasmtime-v0.28.0-x86_64-linux-c-api/lib/libwasmtime.a -lpthread -ldl -lm -o run

# Error
    
    sascha@venezia:~/Dev/wasm_plugin_concept_demo/bugreport$ clang++ run.cc wasm_backend.cc -std=c++20 -I third_party/wasmtime-v0.28.0-x86_64-linux-c-api/include third_party/wasmtime-v0.28.0-x86_64-linux-c-api/lib/libwasmtime.a -lpthread -ldl -lm -o run
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(wasmtime::Func)':
    wasm_backend.cc:(.text+0x310): multiple definition of `wasmtime::Val::Val(wasmtime::Func)'; /tmp/run-b91316.o:run.cc:(.text+0x310): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(wasmtime::ExternRef)':
    wasm_backend.cc:(.text+0x370): multiple definition of `wasmtime::Val::Val(wasmtime::ExternRef)'; /tmp/run-b91316.o:run.cc:(.text+0x370): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(std::optional<wasmtime::Func>)':
    wasm_backend.cc:(.text+0x290): multiple definition of `wasmtime::Val::Val(std::optional<wasmtime::Func>)'; /tmp/run-b91316.o:run.cc:(.text+0x290): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(wasmtime::Func)':
    wasm_backend.cc:(.text+0x310): multiple definition of `wasmtime::Val::Val(wasmtime::Func)'; /tmp/run-b91316.o:run.cc:(.text+0x310): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(wasmtime::ExternRef)':
    wasm_backend.cc:(.text+0x370): multiple definition of `wasmtime::Val::Val(wasmtime::ExternRef)'; /tmp/run-b91316.o:run.cc:(.text+0x370): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::Val(std::optional<wasmtime::Func>)':
    wasm_backend.cc:(.text+0x290): multiple definition of `wasmtime::Val::Val(std::optional<wasmtime::Func>)'; /tmp/run-b91316.o:run.cc:(.text+0x290): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Store::Context::Context(wasmtime::Caller*)':
    wasm_backend.cc:(.text+0x260): multiple definition of `wasmtime::Store::Context::Context(wasmtime::Caller*)'; /tmp/run-b91316.o:run.cc:(.text+0x260): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Store::Context::Context(wasmtime::Caller&)':
    wasm_backend.cc:(.text+0x220): multiple definition of `wasmtime::Store::Context::Context(wasmtime::Caller&)'; /tmp/run-b91316.o:run.cc:(.text+0x220): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Store::Context::Context(wasmtime::Caller*)':
    wasm_backend.cc:(.text+0x260): multiple definition of `wasmtime::Store::Context::Context(wasmtime::Caller*)'; /tmp/run-b91316.o:run.cc:(.text+0x260): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Store::Context::Context(wasmtime::Caller&)':
    wasm_backend.cc:(.text+0x220): multiple definition of `wasmtime::Store::Context::Context(wasmtime::Caller&)'; /tmp/run-b91316.o:run.cc:(.text+0x220): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Caller::get_export(std::basic_string_view<char, std::char_traits<char> >)':
    wasm_backend.cc:(.text+0x460): multiple definition of `wasmtime::Caller::get_export(std::basic_string_view<char, std::char_traits<char> >)'; /tmp/run-b91316.o:run.cc:(.text+0x460): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::wat2wasm(std::basic_string_view<char, std::char_traits<char> >)':
    wasm_backend.cc:(.text+0x50): multiple definition of `wasmtime::wat2wasm(std::basic_string_view<char, std::char_traits<char> >)'; /tmp/run-b91316.o:run.cc:(.text+0x50): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::operator<<(std::ostream&, wasmtime::Error const&)':
    wasm_backend.cc:(.text+0x0): multiple definition of `wasmtime::operator<<(std::ostream&, wasmtime::Error const&)'; /tmp/run-b91316.o:run.cc:(.text+0x0): first defined here
    /usr/bin/ld: /tmp/wasm_backend-8e2203.o: in function `wasmtime::Val::funcref() const':
    wasm_backend.cc:(.text+0x3d0): multiple definition of `wasmtime::Val::funcref() const'; /tmp/run-b91316.o:run.cc:(.text+0x3d0): first defined here

# Description
We just *start* to wrap a `wasm_backend` which *includes* `wasmtime.hh` and is *included* in it's sources AND in one other source (run.cc / main here).  

The test-cases are not catching a problem like that it seems.

Thanks for all your work!
- Sascha

**Comment by alexcrichton** [comment]
Thanks for the report! This is indeed a bug, sorry about that! I've posted a fix in https://github.com/bytecodealliance/wasmtime-cpp/pull/9
